### ISSUE TITLE
Collapsable Settings/Info Sidebar 

### ISSUE THREAD

**Issue by oconorr3** [c0d3ster/Fractaleyez#1]
Create a Collapsable Settings/Info Sidebar like in Atom to display info about the visualizer and offer various setting options for the visualization

**Comment by c0d3ster** [comment]
https://www.npmjs.com/package/jquery-sidebar

simple implementation for us to build off of:
https://github.com/nnattawat/slideReveal

**Comment by c0d3ster** [comment]
closing for now sidebar is not finalized, but the structure for customization and adjusting settings is in place
