### ISSUE TITLE
Additional Input Configuration

### ISSUE THREAD

**Issue by oconorr3** [c0d3ster/Fractaleyez#12]
We need tor provide more customization to control the input parameters for the hopalong algorithm. 

Parameters to add:

1) A, B,C,D,E etc.

2) Number of Particles

3) Different PNG's besides the galaxy one for particles

**Comment by c0d3ster** [comment]
1 is done but we need to rename the parameters to more user friendly values.
2 and 3 require some more work, but we can potentially create an entirely new instance of the visualizer and fade the new one in while fading the new one out if we do have to reinitialize.
